# Generated by Django 3.2.8 on 2021-10-22 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_finch_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food', models.IntegerField(choices=[(1, 'Nyjer Seed'), (2, 'Sunflower Seeds'), (3, 'White Proso Millet'), (4, 'Rapeseed Seeds'), (5, 'Canary Seeds'), (6, 'Shelled And Cracked Corn')], default=2)),
                ('finch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.finch')),
            ],
        ),
    ]
