# Generated by Django 3.2.8 on 2021-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211022_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='parks',
            field=models.ManyToManyField(to='main_app.Park'),
        ),
    ]
